### ISSUE TITLE
Can't visualize benchmark result, graph script is outdated

### ISSUE THREAD

**Issue by jjyr** [noahgibbs/rails_ruby_bench#10]
I get it run on my macbook, and got a json file, but graph script seems broken.

The output json format seems different with graph template. https://github.com/noahgibbs/rails_ruby_bench/tree/master/graph

**Comment by noahgibbs** [comment]
I'm currently out on paternity leave, so I'm afraid you'll be getting slow responses to this... :-)

Short version: yup, you're right and it's outdated. For the blog posts I've been doing for engineering.appfolio.com I've been using D3 rather than Rickshaw. I'll upload what I've been using for that, but they're (mostly) one-off bespoke scripts on the same baseline rather than a good reusable tool you can just drop in.

Here we go. I've uploaded the scripts and data. Here's a good recent example which it may be useful for you to start from:

https://github.com/noahgibbs/rrb_datavis/tree/master/posts/jemalloc

Specifically:

https://github.com/noahgibbs/rrb_datavis/tree/master/posts/jemalloc/jemalloc_run_times.html.erb

You can use this file by running erb on it:

    erb jemalloc_run_times.html.erb > jemalloc_run_times.html && open -a "Google Chrome.app" jemalloc_run_times.html

**Comment by noahgibbs** [comment]
Note to myself: I should link the other repository from the graph directory and remove the outdated attempt.

**Comment by noahgibbs** [comment]
Done.
