### ISSUE TITLE
Running the benchmark locally

### ISSUE THREAD

**Issue by eregon** [noahgibbs/rails_ruby_bench#4]
Hello,

Is it possible to run the benchmark locally, without going through Amazon's AMI setup?
Or alternatively, is there a way to run the AMI and still access the local file system?

This would enable to experiment more freely on a dev machine and ease debugging/performance tuning.

**Comment by noahgibbs** [comment]
That *is* possible, though the README doesn't talk much about how. You can read through packer/ami.json and packer/setup.rb to see what needs to be installed on a machine for that to work. The file start.rb, along with user_simulator.rb, are the actual benchmark. It's designed to be run on a single machine and it's Mac-compatible (I use a Mac,) but it expects access to Postgres.

I haven't optimized much for the local case because it can be tricky to get the right version of everything -- Discourse is fairly finicky, and they have somewhat limited support for running it locally. And of course, my benchmark really requires Discourse to work... Also, it can be hard to keep Discourse properly updated. It's a Rails app, so you'll need to do things like DB migrations if you just "git pull" in place instead of rebuilding. It's possible, but it's the usual kinds of annoying.

What I generally do is run the AMI and scp files back and forth. There's also a directory on the AMI that is exposed via NGINX by default (/var/www/html). Anything you copy there can be fetched via HTTP, and NGinX autoindex is active for that directory, so you can see the file list.

I don't know of a good way to mount an EC2 instance's directory locally and copy back and forth. If you do, I could add any necessary support for it. It's possible to use NFS, but I worry about both security and performance in that case.
